# Generated by Django 4.2.20 on 2025-07-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=5000, unique=True, verbose_name='DeviceId')),
                ('device_type', models.CharField(blank=True, max_length=500, null=True, verbose_name='DeviceType')),
                ('device_type_name', models.CharField(max_length=500, verbose_name='DeviceSpecificType')),
                ('is_connected', models.BooleanField(default=False, verbose_name='Connected')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_seen', models.DateTimeField(auto_now_add=True, verbose_name='Last_Login')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='time_stamp')),
                ('device_id', models.CharField(blank=True, max_length=500, null=True)),
                ('NMR', models.CharField(blank=True, max_length=500, null=True)),
                ('digital_input_status', models.CharField(blank=True, max_length=500, null=True)),
                ('digital_output_status', models.CharField(blank=True, max_length=500, null=True)),
                ('analog_input_1', models.CharField(blank=True, max_length=500, null=True)),
                ('analog_input_2', models.CharField(blank=True, max_length=500, null=True)),
                ('frame_number', models.CharField(blank=True, max_length=500, null=True)),
                ('odometer', models.CharField(blank=True, max_length=500, null=True)),
                ('debug_info', models.CharField(blank=True, max_length=500, null=True)),
                ('header', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=500, null=True)),
                ('version', models.CharField(blank=True, max_length=500, null=True)),
                ('packet_type', models.CharField(blank=True, max_length=500, null=True)),
                ('alert_id', models.CharField(blank=True, max_length=500, null=True)),
                ('packet_status', models.CharField(blank=True, max_length=500, null=True)),
                ('IMEI', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle_reg_no', models.CharField(blank=True, max_length=500, null=True)),
                ('gps_fix', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('longitude', models.CharField(blank=True, max_length=500, null=True)),
                ('longitude_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('speed', models.CharField(blank=True, max_length=500, null=True)),
                ('heading', models.CharField(blank=True, max_length=500, null=True)),
                ('no_of_stattalites', models.CharField(blank=True, max_length=500, null=True)),
                ('altitude', models.CharField(blank=True, max_length=500, null=True)),
                ('pdop', models.CharField(blank=True, max_length=500, null=True)),
                ('hdop', models.CharField(blank=True, max_length=500, null=True)),
                ('operator', models.CharField(blank=True, max_length=500, null=True)),
                ('ignition', models.CharField(blank=True, max_length=500, null=True)),
                ('main_power_status', models.CharField(blank=True, max_length=500, null=True)),
                ('main_input_voltage', models.CharField(blank=True, max_length=500, null=True)),
                ('internal_battery_voltage', models.CharField(blank=True, max_length=500, null=True)),
                ('emergency_status', models.CharField(blank=True, max_length=500, null=True)),
                ('temper_alert', models.CharField(blank=True, max_length=500, null=True)),
                ('gsm_strength', models.CharField(blank=True, max_length=500, null=True)),
                ('MCC', models.CharField(blank=True, max_length=500, null=True)),
                ('MNC', models.CharField(blank=True, max_length=500, null=True)),
                ('LAC', models.CharField(blank=True, max_length=500, null=True)),
                ('cell_id', models.CharField(blank=True, max_length=500, null=True)),
                ('extra_data', models.JSONField()),
                ('can_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=5000, unique=True, verbose_name='DeviceId')),
                ('last_seen', models.DateTimeField(auto_now_add=True, verbose_name='Last_Login')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Notified')),
            ],
        ),
    ]
