# Generated by Django 4.2.20 on 2025-07-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicaDevices',
            fields=[
            ],
            options={
                'verbose_name': 'Replica Device',
                'verbose_name_plural': 'Replica Devices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('devices.device',),
        ),
    ]
