# Generated by Django 4.2.20 on 2025-07-23 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_replicadevices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.TextField()),
                ('alert_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReplicaDevicesData',
            fields=[
            ],
            options={
                'verbose_name': 'Replica DeviceData',
                'verbose_name_plural': 'Replica DevicesData',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('devices.devicedata',),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.devicedata')),
            ],
        ),
    ]
