# Generated by Django 4.2.20 on 2025-07-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_replicadevices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicaDevicesData',
            fields=[
            ],
            options={
                'verbose_name': 'Replica DeviceData',
                'verbose_name_plural': 'Replica DevicesData',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('devices.devicedata',),
        ),
    ]
